server.port=8081
spring.application.name=SpringProject
google.generative.ai.api.key=AIzaSyD9tWxMwVEtrIA_79dD0qXgPndouVZ_8PA


# Database connection settings
spring.datasource.url=jdbc:mysql://localhost:3306/generartive_ai
spring.datasource.username=root
spring.datasource.password=root

# Driver class name
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
